config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:index, :show, :edit, :update]
  resources :posts, only: [:edit, :create, :index, :show, :update, :destroy] do
    collection do
      get '/posts/search', to: 'posts#search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
   enum prefectures_select:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
   }
   
   attachment :image
   validates :onsen_place, presence: true
   validates :onsen_name, presence: true
   validates :caption, presence: true, length: {maximum: 300}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :posts, dependent: :destroy
   attachment :profile_image
   validates :name, uniqueness: true, length: {maximum: 20, minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
    user_path(resource)
end

def after_sign_out_path_for(resource)
    root_path
end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
 def top
 end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    @post=Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post), notice: "You have created  successfully."
    else
      @posts = Post.all
      render 'index'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
    @post= Post.find(params[:id])
    @user = current_user
  end

  def update
    @post= Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def search
    @post = Post.new
    if params[:onsen_place].present?
      @posts = Post.where('onsen_place LIKE ?', "%#{params[:onsen_place]}%")
    else
      @posts = Post.none
    end
    render "index"
  end

private

  def post_params
    params.require(:post).permit(:postal_code, :prefectures_select, :onsen_place, :onsen_name, :image, :caption)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @post = Post.new
    @users = User.all

  end

  def index

    @users = User.all
    @post = Post.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

   private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :prefectures_select)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<%= stylesheet_link_tag 'homes' %>
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to </strong>onnsen base  !!</h1>
      <p>ここは新しい温泉を開拓したい人や温泉について情報収集したい人に向けた交流場所です。

      <p>温泉について情報共有しよう！特にマイナーで知らない人が多いような場所をみんなで語ろう！もちろん有名な場所も歓迎。全国のまだ知らない温泉について知るきっかけとなれたら嬉しいです！！</p>
      <div class="btn-wrapper col-10 mx-auto">
    </div>
        <div class="row">
          <%= link_to 'ログイン',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to '新規登録',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight TAKUYA.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <%= image_tag asset_path("1181936.jpg"),size: "90x60",style: "background-color: white" %>
        <span>温泉基地</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <%= form_with url: posts_search_posts_path, method: :get, local: true do |f| %>
              <%= f.text_field :onsen_place %>
              <%= f.submit :search %>
            <% end %>
            <li><%= link_to ' Home',user_path(current_user),class: 'fas fa-home nav-link text-light' %></li>
            <li><%= link_to ' Users',users_path,class: 'fas fa-users nav-link text-light' %></li>
            <li><%= link_to 'ポスト',posts_path ,class: 'fas fa-comments nav-link text-light'%></li>
            <li><%= link_to ' ログアウト', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
          <% else %>
            <li><%= link_to ' Home',root_path,class: 'fas fa-home nav-link text-light' %></li>
            <li><%= link_to ' 新規登録', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
            <li><%= link_to ' ログイン', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnnsenBase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
   <%= render 'layouts/header' %> 
    <main>
        <p id="notice"><%= notice %></p>
        <%= yield %>
        </main>
   <%= render 'layouts/footer' %>
  </body>
</html>

app/views/post/index.html.erb
<% @posts.each do |post| %>
<div>
  <%= attachment_image_tag post, :image %>
  <p>投稿ユーザー画像：<%= image_tag('') %></p>
  <p>温泉場所：<%= post.onsen_place %></p>
  <p>温泉名：<%= post.onsen_name %></p>
  <p>説明：<%= post.caption %></p>
  <p>ユーザーネーム：<%= post.user.name %></p>

</div>
<% end %>

app/views/post/new.html.erb
<h1>投稿フォーム</h1>
<%= form_with model: @post, local:true do |f| %>
  <h4>温泉場所</h4>
  <%= f.text_field :onsen_place %>
  <h4>温泉名</h4>
  <%= f.text_field :onsen_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <% end %>

app/views/posts/_form.html.erb
<h1>投稿フォーム</h1>
<%= form_with model: @post, local:true do |f| %>
  <h4>温泉場所</h4>
  <p>郵便番号（ハイフン不要）</p>
  <%= f.text_field :postal_code %>
  <p>住所</p>
  <%= f.select :prefectures_select, Post.prefectures_selects.keys, {} %>
  <%= f.text_field :onsen_place %>
  <h4>温泉名</h4>
  <%= f.text_field :onsen_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
 <% end %>
 

app/views/posts/_index.html.erb
<% @posts.each do |post| %>
<div>
  <%= link_to post_path(post) do %>
    ユーザー画像：<%= attachment_image_tag(@user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg") %><br><br>
    ユーザーネーム：<%= post.user.name %><br><br>
    温泉場所<br><br>
   　郵便番号:<%= post.postal_code %><br><br>
         住所:<%= post.prefectures_select %>
             :<%= post.onsen_place %><br><br>
    温泉名：<%= post.onsen_name %><br><br>
    説明：<%= post.caption %><br><br>
    投稿画像:<%= attachment_image_tag(post, :image, :fill, 150, 150, fallback: '') %>
    日時：<%= l post.created_at %><br><br>

  <% end %>

</div>
<% end %>

app/views/posts/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>投稿内容の変更</h1>
    	<%= render 'layouts/errors', obj: @post %>
  		<%= render 'form', post: @post %>
  		<%= link_to 'Show', post_path(@post), class: "post_#{@post.id}" %> |
  		<%= link_to 'Back', posts_path, class: "back" %>
  </div>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'posts' %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h3><%= @post.errors.count %>error prohibited this obj from being saved:</h3>
         <ul>
           <% @post.errors.full_messages.each do |message| %>
             <li><%= message %></li>
           <% end %>
         </ul>
       </div>
    <% end %>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/profile', user: current_user %>
      <h2 class="mt-3"></h2>
      <%= render 'form', post: @post %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>投稿一覧</h2>
      <%= render 'index', posts: @posts%>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag 'posts' %>
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/profile', user: @user, users: @users %>
      <h2 class="mt-3"></h2>
      <%= render 'form', post: @post %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<table border="1">
  		  <h2>投稿一覧</h2>
        <tr>
           <td>　ユ　ー　ザ　ー　名　</td>
           <td>　温　泉　場　所</td>
           <td>　温　泉　名</td>
        </tr>
　　　</table>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@post.user) do %>
            <%= attachment_image_tag(@post.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %><br>
            <%= @post.user.name %>
            <% end %>
          </td>
          <td><%= link_to @post.onsen_place, post_path(@post) %></td>
          <td><%= @post.onsen_name %></td>
          <td><%= @post.caption %></td>
          <% if @post.user_id == current_user.id %>

          　<td><%= link_to 'Edit', edit_post_path(@post), class: "btn btn-sm btn-success edit_book_#{@post.id}" %></td>
          　<td><%= link_to 'Destroy', post_path(@post), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_post_#{@post.id}"%></td>
          <% end %>
        </tr>
        <tr>
        <td colspan="4"><div id='map'>
          </div></td>
        </tr>
      </table>
    </div>
  </div>
</div>


<div id='map'>
</div>

<style>
#map{
  height: 400px;
}
</style>

<script>
let map
let geocoder

function initMap(){
  // geocoderを初期化
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: -34.397, lng: 150.644},
  zoom: 8
  });


  // 入力を取得
  let onsen_place = '<%= @post.prefectures_select %><%= @post.onsen_place %>';

  // geocodingしたあとmapを移動
  geocoder.geocode( { 'address': onsen_place}, function(results, status) {
    if (status == 'OK') {
　　　　　　　　　　　　// map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);

　　　　　　　　　　　　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBN_tybKQrAruaJFjX3vtKIbjWtOcvOgQs&callback=initMap" async defer></script>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>
<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'users' %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'profile', user: current_user %>
      <h2 class="mt-3"></h2>
      <%= render 'posts/form', post: @post %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>ユーザー一覧</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'profile', user: @user, users: @users %>
      <h2 class="mt-3"></h2>
      <%= render 'posts/form', post: @post %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2><%= @user.name %>の投稿履歴</h2>
      <%= render 'posts/index',post: @posts %>
    </div>
  </div>
</div>